name: Runner
on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

concurrency:
  group: runner
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Runner
        run: |
          sudo sed -i -E 's|ExecStart=/usr/bin/dockerd.*|ExecStart=/usr/bin/dockerd -H fd:// -H tcp://localhost:2375|g' /lib/systemd/system/docker.service && \
          sudo systemctl daemon-reload && \
          sudo systemctl restart docker && \
          sudo mkdir -p /etc/apt/keyrings && \
          curl -fsSL https://archive.heckel.io/apt/pubkey.txt | sudo gpg --dearmor -o /etc/apt/keyrings/archive.heckel.io.gpg && \
          sudo apt install -y apt-transport-https && \
          sudo sh -c "echo 'deb [arch=amd64 signed-by=/etc/apt/keyrings/archive.heckel.io.gpg] https://archive.heckel.io/apt debian main' > /etc/apt/sources.list.d/archive.heckel.io.list" && \
          sudo apt update && \
          sudo apt install -y ntfy expect && \
          wget -O ./onionpipe https://github.com/cmars/onionpipe/releases/download/v1.1.11/onionpipe-linux-amd64-static && \
          chmod 755 ./onionpipe

          start_onionpipe(){

          pkill -9 -f ./onionpipe || true

          rm -rf ./onion_url.txt

          (
          expect -c '
              spawn ./onionpipe 2375~2375
              set timeout 999999
              expect {
                  -re {.*=> *([a-z0-9]+\.onion):2375} {
                      set onion $expect_out(1,string)
                      exec echo $onion > ./onion_url.txt
                      exp_continue
                  }
              }
          ' >/dev/null 2>&1 &
          )

          while true; do
              unset onion_url
              onion_url=$(cat ./onion_url.txt 2>/dev/null || true)

              if [[ "$onion_url" =~ ^[a-z0-9]+\.onion$ ]]; then
                  echo "Captured valid Onion URL"
                  break
              fi

              sleep 1
          done

          while true; do
              ntfy publish "ntfy${{ secrets.RUNNER_SECRET }}" "$onion_url" >/dev/null 2>&1
              sleep 10
          done
          }

          start_onionpipe &

          while true; do
              echo running >/dev/null 2>&1
              sleep 5
          done   
